- hosts: NameNode
  vars_files:
          - var.yml
  tasks:
          - name: Copy Java Software
            copy:
                    src: "/root/arth-ws/softwares/jdk-8u171-linux-x64.rpm"
                    dest: "/root/"

          - name: Copy Hadoop Software
            copy:
                    src: "/root/arth-ws/softwares/hadoop-1.2.1-1.x86_64.rpm"
                    dest: "/root/"

          - name: Install Java Software
            shell: "rpm -i /root/jdk-8u171-linux-x64.rpm"
            register: java_install

          - name: java install information
            debug:
                    var: java_install

          - name: Install Hadoop Software
            shell: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"
            register: hadoop_install
            when: java_install.rc == 0

          - name: hadoop install information
            debug:
                    var: hadoop_install

          - name: Create Directory
            file:
                    state: directory
                    path: "{{ name_dir }}"

          - name: Copy hdfs-site.xml file
            template:
                    src: "n_hdfs-site.xml"
                    dest: "/etc/hadoop/hdfs-site.xml"

          - name: Copy core-site.xml file
            template:
                    src: "n_core-site.xml"
                    dest: "/etc/hadoop/core-site.xml"

          - name: Format the namenode directory
            shell: "echo Y | hadoop namenode -format"

          - name: Start NameNode Service
            shell: "hadoop-daemon.sh start namenode"

- hosts: DataNode
  vars_files:
          - var.yml
  tasks:
          - name: Copy Java Software
            copy:
                    src: "/root/arth-ws/softwares/jdk-8u171-linux-x64.rpm"
                    dest: "/root/"

          - name: Copy Hadoop Software
            copy:
                    src: "/root/arth-ws/softwares/hadoop-1.2.1-1.x86_64.rpm"
                    dest: "/root/"

          - name: Install Java Software
            shell: "rpm -i /root/jdk-8u171-linux-x64.rpm"
            register: java_install

          - name: java install information
            debug:
                    var: java_install

          - name: Install Hadoop Software
            shell: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"
            register: hadoop_install
            when: java_install.rc == 0

          - name: hadoop install information
            debug:
                    var: hadoop_install

          - name: Create Directory
            file:
                    state: directory
                    path: "{{ data_dir }}"

          - name: Copy hdfs-site.xml file
            template:
                    src: "d_hdfs-site.xml"
                    dest: "/etc/hadoop/hdfs-site.xml"

          - name: Copy core-site.xml file
            template:
                    src: "d_core-site.xml"
                    dest: "/etc/hadoop/core-site.xml"

          - name: Start DataNode Service
            shell: "hadoop-daemon.sh start datanode"
